# Generated by Django 3.0.5 on 2020-05-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.CharField(max_length=2800, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=2800, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.CharField(max_length=2800, null=True),
        ),
    ]
